"""add review timestamps

Revision ID: a95df227d3da
Revises: e743e975bfff
Create Date: 2026-05-11 23:46:49.865591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a95df227d3da'
down_revision: Union[str, Sequence[str], None] = 'e743e975bfff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('reviews', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'updated_at')
    op.drop_column('reviews', 'created_at')
    # ### end Alembic commands ###
